import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tournament_ui, TournamentUiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Bind to loopback by default. Set PHX_LISTEN_ALL=1 to bind to 0.0.0.0
  # — required when this host fronts the Phoenix dev server through a
  # reverse proxy on a different machine (e.g. tournaments.example.com on
  # a gateway host proxying to this workstation over a private network).
  http: [
    ip:
      if System.get_env("PHX_LISTEN_ALL") in ["1", "true"] do
        {0, 0, 0, 0}
      else
        {127, 0, 0, 1}
      end,
    port: String.to_integer(System.get_env("PORT", "4000"))
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bqRJanbGWIcjW+Vf35Dllc67BKGSTFnMgczYyv05WiCxqV0gdMXJR6n1zMzKPURu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tournament_ui, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tournament_ui, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
#
# The native macOS watcher binary (mac_listener) is not packaged in the Nix
# dev shell, so the default file_system backend can never start and browsers
# log "live reload backend not running" every ~10s. Poll instead: slightly
# laggier, works everywhere.
config :phoenix_live_reload,
  backend: :fs_poll,
  backend_opts: [interval: 1_000]

config :tournament_ui, TournamentUiWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/tournament_ui_web/router\.ex$",
      ~r"lib/tournament_ui_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tournament_ui, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
